Update export2.yml

diff --git a/.github/workflows/export2.yml b/.github/workflows/export2.yml
--- a/.github/workflows/export2.yml
+++ b/.github/workflows/export2.yml
@@ -23,17 +23,27 @@ jobs:
 
     - name: Download file with curl
       run: |
-        curl -o ${{ github.workspace }}$TARGET_FILEPATH -u "${{ secrets.POOLPARTY_USERNAME }}:${{ secrets.POOLPARTY_PASSWORD }}" -H "Content-Type: application/json" -d '{
+        response=$(curl -o ${{ github.workspace }}$TARGET_FILEPATH -u "${{ secrets.POOLPARTY_USERNAME }}:${{ secrets.POOLPARTY_PASSWORD }}" -H "Content-Type: application/json" -d '{
           "prettyPrint": true,
           "format": "TriG",
           "modules": [ "concepts" ]
-        }' $POOLPARTY_API_ENDPOINT/projects/$PROJECT_NAME/export
+        }' $POOLPARTY_API_ENDPOINT/projects/$PROJECT_NAME/export)
+        
+        exit_code=$?
+
+        if [ $exit_code -ne 0 ]; then
+          echo "Curl command failed with exit code $exit_code"
+          echo "$response"
+          exit $exit_code
+        fi
+      env:
+        TARGET_FILEPATH: ${{ env.TARGET_FILEPATH }}
+        POOLPARTY_API_ENDPOINT: ${{ env.POOLPARTY_API_ENDPOINT }}
+        PROJECT_NAME: ${{ env.PROJECT_NAME }}
 
     - name: Commit and push
       if: success()
       run: |
-        git config user.name github-actions[bot]
-        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
         git add $TARGET_FILEPATH
         git commit -m 'Scheduled PoolParty Thesaurus Backup'
         git push
